<?php

declare(strict_types=1);

$autoloader_deprecated = DIR_FS_DOCUMENT_ROOT . '/vendor-no-composer/autoload.php';
$autoloader = DIR_FS_DOCUMENT_ROOT . '/vendor-mmlc/autoload.php';

if (file_exists($autoloader)) {
    require_once $autoloader;
} elseif (file_exists($autoloader_deprecated)) {
    require_once $autoloader_deprecated;
} else {
    trigger_error(
        'MMLC Module composer/autoload notice: can`t find file: ' .
        $autoloader . ' ' .
        ' This file is generated by the MMLC.',
        E_USER_NOTICE
    );
}
